### ISSUE TITLE
"Future" KYC example UI changes

### ISSUE THREAD

**Issue by nitzanballerine** [ballerine-io/ballerine#102]
### Description
In order to make the experience of the "Future" KYC example UI more appealing, please provide the following UI changes.

### Tasks
- [x] Change the paragraphs font color to white
- [ ] Change the CTA on the success and failure screens' buttons to “Close”
- [ ] Clicking on the success and failure screens CTA should redirect to Ballerine’s GitHub
- [ ] Add  margins from the top of the "card back side" and "Selfie" illustrations (margin: 12vh auto;)

### Examples and references
Enter: https://examples-future.ballerine.app/ and see the colors and texts throughout the flow.

**Comment by mchav** [comment]
Will this be kept as a revolving first issue or is it something y'all want changed in the example.

**Comment by nitzanballerine** [comment]
Hi @mchav , these are some small changes we want the example to have, so once this issue is done we will close it.
